name: Create Release After Tag

on:
  workflow_run:
    workflows: ["Create Tag on Commit"]
    types:
      - completed
    branches:
      - main

jobs:
  create-release:
    # Only run if the tag workflow was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get commit details
        id: commit-details
        run: |
          set -x
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "commit_msg=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT
          set +x

      - name: Get latest tag
        id: get-tag
        run: |
          # Get the latest tag created by the auto-tag workflow
          git fetch --tags
          LATEST_TAG=$(git tag -l "v*" | sort -V | tail -n 1)
          
          if [ -z "$LATEST_TAG" ]; then
            echo "Error: No tags found" >&2
            exit 1
          fi
          
          echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT
          echo "Found latest tag: $LATEST_TAG"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.get-tag.outputs.tag }}
          tag_name: ${{ steps.get-tag.outputs.tag }}
          body: |
            Automated release ${{ steps.get-tag.outputs.tag }}
            
            Commit SHA: ${{ steps.commit-details.outputs.sha_short }}
            Commit message: ${{ steps.commit-details.outputs.commit_msg }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

